"""empty message

Revision ID: 6be56f00ae7e
Revises: 5e4961b09d63
Create Date: 2022-03-09 14:24:03.225894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6be56f00ae7e'
down_revision = '5e4961b09d63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'full_name',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=240),
               existing_nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=240),
               existing_nullable=False)
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=240),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.String(length=240),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.String(length=240),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
    op.alter_column('user', 'full_name',
               existing_type=sa.String(length=240),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
    # ### end Alembic commands ###
