"""empty message

Revision ID: 76d297aa18dc
Revises: 2807edd385a2
Create Date: 2022-03-02 14:23:51.221841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76d297aa18dc'
down_revision = '2807edd385a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cardInfoNum', sa.Integer(), nullable=False),
    sa.Column('cardInfoDate', sa.Integer(), nullable=False),
    sa.Column('cardInfoCVC', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cardInfoCVC'),
    sa.UniqueConstraint('cardInfoDate'),
    sa.UniqueConstraint('cardInfoNum')
    )
    op.create_table('chef',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('fullName', sa.String(length=120), nullable=False),
    sa.Column('chefDescription', sa.String(length=400), nullable=False),
    sa.Column('bankInfo', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bankInfo'),
    sa.UniqueConstraint('email')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('fullName', sa.String(length=120), nullable=False),
    sa.Column('studentDescription', sa.String(length=400), nullable=False),
    sa.Column('address', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('courseName', sa.String(length=120), nullable=False),
    sa.Column('dificulty', sa.String(length=20), nullable=False),
    sa.Column('style', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=False),
    sa.Column('ingredient', sa.String(length=50), nullable=False),
    sa.Column('listIngredient', sa.String(length=200), nullable=False),
    sa.Column('requeriments', sa.String(length=50), nullable=False),
    sa.Column('knowledge', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('video', sa.String(length=240), nullable=False),
    sa.Column('chef_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chef_id'], ['chef.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('student_id', 'course_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags')
    op.drop_table('course')
    op.drop_table('student')
    op.drop_table('chef')
    op.drop_table('card_info')
    # ### end Alembic commands ###
