"""empty message

Revision ID: 8795089ac04f
Revises: 
Create Date: 2022-03-06 15:07:03.476433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8795089ac04f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cardinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cardInfoNum', sa.Integer(), nullable=False),
    sa.Column('cardInfoDate', sa.Integer(), nullable=False),
    sa.Column('cardInfoCVC', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cardInfoCVC'),
    sa.UniqueConstraint('cardInfoDate'),
    sa.UniqueConstraint('cardInfoNum')
    )
    op.create_table('chef',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('chef_description', sa.String(length=400), nullable=False),
    sa.Column('bank_info', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bank_info'),
    sa.UniqueConstraint('email')
    )
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=120), nullable=False),
    sa.Column('dificulty', sa.String(length=20), nullable=False),
    sa.Column('style', sa.String(length=200), nullable=False),
    sa.Column('country', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('ingredient', sa.String(length=200), nullable=False),
    sa.Column('list_ingredient', sa.String(length=200), nullable=False),
    sa.Column('requeriments', sa.String(length=200), nullable=False),
    sa.Column('knowledge', sa.String(length=200), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('video', sa.String(length=240), nullable=False),
    sa.Column('img', sa.String(length=240), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_name'),
    sa.UniqueConstraint('img'),
    sa.UniqueConstraint('video')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('student_description', sa.String(length=400), nullable=True),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('facebook_url', sa.String(length=120), nullable=True),
    sa.Column('instagram_url', sa.String(length=120), nullable=True),
    sa.Column('linkedin_url', sa.String(length=120), nullable=True),
    sa.Column('twitter_url', sa.String(length=120), nullable=True),
    sa.Column('website_url', sa.String(length=120), nullable=True),
    sa.Column('image', sa.String(length=240), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('image'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('tags',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('student_id', 'course_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags')
    op.drop_table('user')
    op.drop_table('student')
    op.drop_table('course')
    op.drop_table('chef')
    op.drop_table('cardinfo')
    # ### end Alembic commands ###
