"""empty message

Revision ID: bfda51a0dcee
Revises: 6be56f00ae7e
Create Date: 2022-03-09 14:56:37.466848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfda51a0dcee'
down_revision = '6be56f00ae7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'linkedin_url')
    op.drop_column('user', 'facebook_url')
    op.drop_column('user', 'twitter_url')
    op.drop_column('user', 'instagram_url')
    op.drop_column('user', 'website_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('website_url', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('instagram_url', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('twitter_url', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('facebook_url', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('linkedin_url', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
