"""empty message

Revision ID: ea15ea040be6
Revises: f3cc8fb7f722
Create Date: 2022-03-03 11:26:49.543620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea15ea040be6'
down_revision = 'f3cc8fb7f722'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('student_id', 'course_id')
    )
    op.add_column('course', sa.Column('chef_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'course', 'chef', ['chef_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'course', type_='foreignkey')
    op.drop_column('course', 'chef_id')
    op.drop_table('tags')
    # ### end Alembic commands ###
