"""empty message

Revision ID: ef36e4de59f3
Revises: 
Create Date: 2022-03-28 07:14:25.478283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef36e4de59f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cardinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cardInfoNum', sa.Integer(), nullable=False),
    sa.Column('cardInfoDate', sa.Integer(), nullable=False),
    sa.Column('cardInfoCVC', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cardInfoCVC'),
    sa.UniqueConstraint('cardInfoDate'),
    sa.UniqueConstraint('cardInfoNum')
    )
    op.create_table('chef',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('chef_description', sa.String(length=400), nullable=False),
    sa.Column('bank_info', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bank_info'),
    sa.UniqueConstraint('email')
    )
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('ingredient', sa.String(length=200), nullable=False),
    sa.Column('list_ingredient', sa.String(length=500), nullable=False),
    sa.Column('recipe', sa.String(length=1000), nullable=False),
    sa.Column('history', sa.String(length=1000), nullable=False),
    sa.Column('curiosity', sa.String(length=1000), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('video', sa.String(length=500), nullable=False),
    sa.Column('img', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_name'),
    sa.UniqueConstraint('img'),
    sa.UniqueConstraint('video')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=240), nullable=False),
    sa.Column('email', sa.String(length=240), nullable=False),
    sa.Column('password', sa.String(length=240), nullable=False),
    sa.Column('student_description', sa.String(length=400), nullable=True),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('image', sa.String(length=240), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('course')
    op.drop_table('chef')
    op.drop_table('cardinfo')
    # ### end Alembic commands ###
