"""empty message

Revision ID: f3cc8fb7f722
Revises: 
Create Date: 2022-03-03 11:15:02.782936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3cc8fb7f722'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cardInfoNum', sa.Integer(), nullable=False),
    sa.Column('cardInfoDate', sa.Integer(), nullable=False),
    sa.Column('cardInfoCVC', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cardInfoCVC'),
    sa.UniqueConstraint('cardInfoDate'),
    sa.UniqueConstraint('cardInfoNum')
    )
    op.create_table('chef',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('fullName', sa.String(length=120), nullable=False),
    sa.Column('chefDescription', sa.String(length=400), nullable=False),
    sa.Column('bankInfo', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bankInfo'),
    sa.UniqueConstraint('email')
    )
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=120), nullable=False),
    sa.Column('dificulty', sa.String(length=20), nullable=False),
    sa.Column('style', sa.String(length=200), nullable=False),
    sa.Column('country', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('ingredient', sa.String(length=200), nullable=False),
    sa.Column('list_ingredient', sa.String(length=200), nullable=False),
    sa.Column('requeriments', sa.String(length=200), nullable=False),
    sa.Column('knowledge', sa.String(length=200), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('video', sa.String(length=240), nullable=False),
    sa.Column('img', sa.String(length=240), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_name'),
    sa.UniqueConstraint('img'),
    sa.UniqueConstraint('video')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('fullName', sa.String(length=120), nullable=False),
    sa.Column('studentDescription', sa.String(length=400), nullable=True),
    sa.Column('nickName', sa.String(length=120), nullable=False),
    sa.Column('facebookURL', sa.String(length=120), nullable=True),
    sa.Column('instagramURL', sa.String(length=120), nullable=True),
    sa.Column('linkedinURL', sa.String(length=120), nullable=True),
    sa.Column('twitterURL', sa.String(length=120), nullable=True),
    sa.Column('websiteURL', sa.String(length=120), nullable=True),
    sa.Column('image', sa.String(length=240), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('image'),
    sa.UniqueConstraint('nickName')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('student')
    op.drop_table('course')
    op.drop_table('chef')
    op.drop_table('card_info')
    # ### end Alembic commands ###
